### PR TITLE
Fix xdg email

### PR DESCRIPTION
**Pull request by mlopezcoria**
Fixed launchpad bug #1469840: Error taking a screenshot and selecting the option Send by email (Ctrl+Shift+E)

### CODE REVIEW

**Comment by mlopezcoria** [comment]
I just changed line 6971 to correct this error and +1 on Rev.

**Comment by dniku** [comment]
Thank you for your PR. Please note that this is *not* an official repository, but rather a fork that I created with the sole purpose of publishing a fix for a segfault.

That said, I'm not sure about updating the revision. I did not know about it when I was publishing my patch, and now I'm thinking whether I should update it because the code is no longer identical to the one in the official repository. What is it used for?

**Comment by mlopezcoria** [comment]
Thank you for your answer. I didn't find other repo so I thought it was the one :-P Also I think shutter is on longer maintained because there's no new version since 2014.
I use Shutter Linux mint from the official repos and it has this code version. I think you have the last version in this repository. 

Best regards!

**Comment by dniku** [comment]
I have [merged](https://github.com/Pastafarianist/shutter/commit/d28811bd104597d7c53ae2c36419e5e489612892) your changes, although I have changed them manually first. Closing this PR.

**Pull request closed without merging**
